apiVersion: v1
kind: Service
namespace: {{.Values.namespace}}
metadata:
  name: pdf-grafana
  namespace: {{.Values.namespace}}
spec:
  ports:
  - protocol: TCP
    port: 8686
    targetPort: 8686
  selector:
    app: pdf-grafana