apiVersion: v1
kind: Service
metadata:
  labels:
    app: pdf-grafana
  name: testsvc
  namespace: {{.Values.namespace}}
spec:
  ports:
  - nodePort: 30679
    port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    app: pdf-grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}