apiVersion: extensions/v1beta1
kind: Deployment
namespace: {{.Values.namespace}}
metadata:
  name: preconsumer
  namespace: {{.Values.namespace}}
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: consumer
    spec:
      nodeSelector:
        workerNode: "yes"
      containers:
      - name: consumer
        image: r0486682/pause
        args: ["exit 0"]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{.Values.worker3CPU}}
          limits:
            cpu: {{.Values.worker3CPU}}
      priorityClassName: {{.Values.priorityClass}}
      terminationGracePeriodSeconds: 600
