apiVersion: v1
kind: Service
namespace: {{.Values.namespace}}
metadata:
  name: graphite
  namespace: {{.Values.namespace}}
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: graphite