apiVersion: extensions/v1beta1
kind: Deployment
namespace: {{.Values.namespace}}
metadata:
  name: consumer3
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.worker3Replicas}}
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: r0486682/java-consumer:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{.Values.worker3CPU}}
          limits:
            cpu: {{.Values.worker3CPU}}
        env:
        - name: DNS_NAMESPACE
          value: {{.Values.namespace}}
        - name: STRESS_SIZE
          value: "{{.Values.stressSize}}"
        - name: POOL_SIZE
          value: "{{.Values.poolSize3}}"          
      priorityClassName: {{.Values.priorityClass}}
