apiVersion: v1
kind: Service
namespace: {{.Values.namespace}}
metadata:
  name: consumer
  namespace: {{.Values.namespace}}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
  selector:
    app: consumer