
nbOfIterations: 1
nbOfSamplesPerIteration: 63
charts:
  - name: my-app
    chartdir: conf/helm/mychart
slas:
  - name : silver
    chartName: my-app
    slos: 
      jobsize: 200
      throughput: 0.5
    nbOfTenants: 2
    parameters:
      - name: workerCPU
        searchspace:
          min: 400
          max: 800
          granularity: 20
        prefix: 
        suffix: m
      - name: workerReplicas
        searchspace:
          min: 1
          max: 3
          granularity: 1
        prefix: 
        suffix: 
namespaceStrategy: NSPSLA
optimizer: exhaustive
utilFunc: resourceBased
outputDir: exhaustive4
# prevResultsPath: test/results.json


