
nbOfIterations: 1
nbOfSamplesPerIteration: 1
charts:
  - name: my-app
    chartdir: conf/helm/mychart
slas:
  - name : silver
    chartName: my-app
    slos: 
      jobsize: 100
      throughput: 0.5
    nbOfTenants: 2
    parameters:
      - name: workerCPU
        searchspace:
          min: 400
          max: 400
          granularity: 20
        prefix: 
        suffix: m
      - name: workerReplicas
        searchspace:
          min: 1
          max: 1
          granularity: 1
        prefix: 
        suffix: 
namespaceStrategy: NSPSLA
optimizer: exhaustive
utilFunc: resourceBased
outputDir: bayesiantest
# prevResultsPath: datasets/exhaustive1/results.json
