
nbOfIterations: 3
nbOfSamplesPerIteration: 3
charts:
  - name: newchart
    chartdir: conf/helm/newchart
slas:
  - name : silver
    chartName: newchart
    slos: 
      jobsize: 50
      throughput: 0.5
    nbOfTenants: 2
    parameters:
      - name: consumers.consumer1.cpu
        searchspace:
          min: 100
          max: 200
          granularity: 20
        prefix: 
        suffix: m
      - name: consumers.consumer1.replicas
        searchspace:
          min: 1
          max: 1
          granularity: 1
        prefix: 
        suffix:
  - name : gold
    chartName: newchart
    slos: 
      jobsize: 100
      throughput: 0.5
    nbOfTenants: 1
    parameters:
      - name: consumers.consumer1.cpu
        searchspace:
          min: 200
          max: 600
          granularity: 20
        prefix: 
        suffix: m
      - name: consumers.consumer2.replicas
        searchspace:
          min: 1
          max: 1
          granularity: 1
        prefix: 
        suffix:       
namespaceStrategy: NSPSLA
optimizer: bestconfig
utilFunc: resourceBased
outputDir: Results
# prevResultsPath: datasets/exhaustive1/results.json
