apiVersion: v1
kind: Service
namespace: {{.Values.namespace}}
metadata:
  name: rabbitmq
  namespace: {{.Values.namespace}}
spec:
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq