apiVersion: v1
kind: Service
namespace: {{.Values.namespace}}
metadata:
  name: resource-planner
  namespace: {{.Values.namespace}}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: resource-planner