apiVersion: v1
kind: Service
metadata:
  name: svcext-graphite-web
  labels:
    app.kubernetes.io/name: {{ include "graphite.name" . }}
    helm.sh/chart: {{ include "graphite.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - nodePort: 30690
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "graphite.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}